version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: nestjs-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      JWT_SECRET: HEY
      OTP_CODE: HEY
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/nestjs

volumes:
  mysql-data:
